config/routes.rb
Batterypopv2::Application.routes.draw do


  get 'kpass/authorize' => 'kpass#authorize', as: 'kpass_authorize'
  get 'kpass/profile' => 'kpass#profile', as: 'kpass_profile'
  get 'kpass/verify' => 'kpass#verify', as: 'kpass_verify'
  get 'kpass/sign_out' => 'kpass#sign_out', as: 'kpass_sign_out'
  post 'kpass/webhooks' => 'kpass#webhooks', as: 'kpass_webhooks'
  get 'kpass/new' => 'kpass#new', as: 'kpass_new'


  mount Rich::Engine => '/rich', :as => 'rich'

  resources :channels

  resources :menus

  # resources :contacts
  #

  # mount Split::Dashboard, :at => 'admin/split'

  resources :friends do
    member do
      get :follow
      get :unfollow
    end
    resources :episodes
  end

  # resources :episodes

  resources :posts

  resources :links do
    member do
      get :file
      get :feed
    end
  end

  resources :categories

  resources :tournaments

  get "matches/:id/:episode_id", :to => "tournaments#vote"

  resources :shows do
    member do
      get :follow
      get :unfollow
    end
     resources :episodes
  end

  resources :episodes do
    member do
      get :pop
      get :unpop
      post :refresh
    end
  end

 post "/refresh", :to => "episodes#refresh"

  resources :messages
  resources :conversations


  # sitemap routing
  get "/sitemap.xml", :to => "sitemap#index"
  get "/sitemap.xml.gz", :to => "sitemap#index"

  get 'videotest', :to => "media#index"

  get "/dashboard", :to => "creators#dashboard"
  get "/creators/sign_out", :to => "creators#dashboard"


  # get "pages/search"

  get "shorts", :to => "pages#shorts"
  # get "calling-all-creators", :to => "pages#creators"
  # get "privacy-policy", :to => "pages#privacy"
  # get "terms-and-conditions", :to => "pages#terms"
  # get "advertise-with-us", :to => "pages#advertise"
  # get "about-batterypop", :to => "pages#about"
  # get "investors", :to => "pages#investors"
  get "bot", :to => "pages#bot"

  # get "test", :to => "pages#test"

  get "search", :to => "pages#search"

  get "contact", :to => "contacts#new"
  post "contact", :to => "contacts#create"

  root :to => "pages#home"




  devise_for :users,
    :controllers => {
      :registrations => "devise/custom/registrations",
      :passwords => "devise/custom/passwords",
      :sessions => "devise/custom/users"
    }

  devise_for :creators,
    :controllers => {
       sessions: "devise/custom/creators"
      # :registrations => "devise/custom/creators"
    }

  # devise_for :creators, :skip => [:sessions] do
  #   get '/creator/login' => 'devise/sessions#new', :as => :new_creator_session
  #   post '/creator/login' => 'devise/sessions#create', :as => :creator_session
  #   get 'logout' => 'devise/sessions#destroy', :as => :destroy_creator_session
  # end

    #devise_for :users, path: "auth", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }

resources :users do
    member do
      patch :save_avatar
      get :follow
      get :unfollow
     end
  end

  resources :creators  do
    member do
      post :draw_chart_bar
      post :draw_chart_donut
    end
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)


  get ":id" => "pages#show"

  get '*path' => redirect('/')



end

app/models/friend.rb
# == Schema Information
#
# Table name: episodes
#
#  id                 		:integer          not null, primary key
#  title              		:string(255)
#  description        		:text
#  approved           		:boolean
#  slug               		:string(255)
#  sponsor			  		:string(255)
#  created_at              :datetime
#  updated_at              :datetime
#  image_file_name         :string(255)
#  image_content_type      :string(255)
#  image_file_size         :integer
#  image_updated_at        :datetime
#  background_file_name    :string(255)
#  background_content_type :string(255)
#  background_file_size    :integer
#  background_updated_at   :datetime
#  features_autoplay	   :boolean
#  features_exit		   :string(255)

#  episodes

class Friend < ActiveRecord::Base
	include PgSearch
	# multisearchable :against => [:title, :description, :sponsor]

	after_save :set_search_link

	pg_search_scope :search_text,
                  :against => [:title, :description, :sponsor],
                  :using => {
                    :tsearch => {:prefix => true}
                  }

	extend FriendlyId
	friendly_id :slug_candidates, use: :slugged

	acts_as_followable
	acts_as_taggable_on  :keywords

	has_many :friend_episodes
	# has_many :episodes, -> {order('episodes.created_at ASC')} , :through => :friend_episodes
	has_many :episodes, :through => :friend_episodes
	has_many :episodes_approved, :through => :friend_episodes, :source => :episode
	has_many :shows, :through => :episodes

	 # -> { select('company_stores.*, customers.name').order('company_stores.id ASC').uniq },
	 # -> { order('created_at DESC') },
	 # -> { select('episodes.*').order('created_at ASC') }
	
	has_many :features, :as => :owner

	accepts_nested_attributes_for :features

	before_save :destroy_images?

	#image stuff
	#
	has_attached_file :sidebar_image,
	    :styles => { large: "400x390>", :thumb => "100x100>"},
	    storage: :s3,
	    s3_credentials: "#{Rails.root}/config/amazon_s3.yml",
	    path: "images/friends/:id/sidebar_image/:attachment/:style/:filename",
	    bucket: S3_BUCKET,
	    default_url: "/assets/missing.png"

	has_attached_file :image,
	    :styles => { large: "300x300>", listing: "200x200>", :thumb => "150x150>" },
	    storage: :s3,
	    s3_credentials: "#{Rails.root}/config/amazon_s3.yml",
	    path: "images/friends/:id/image/:attachment/:style/:filename",
	    bucket: S3_BUCKET,
	    default_url: "/assets/missing.png"

	has_attached_file :background,
	    :styles => { full: "1600x1100>", large: "300x300>",  :thumb => "100x100>" },
	    storage: :s3,
	    s3_credentials: "#{Rails.root}/config/amazon_s3.yml",
	    path: "images/friends/:id/background/:attachment/:style/:filename",
	    bucket: S3_BUCKET

	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
	validates_attachment_content_type :background, :content_type => /\Aimage\/.*\Z/

	scope :approved, -> {where(:approved => true)}

	def link
		"/friends/" + self.slug
	end

	def episode_link(episode)
		self.link + '/episodes/' + episode.slug
	end

	def should_generate_new_friendly_id?
	  slug.blank? || title_changed?
	end

	# pg search fixes
def set_search_link
	ret = PgSearchDocuments.where(searchable_id: self.id, searchable_type: self.class.name)
	if ret.count
		ret.each do |d|
			d.delete
		end
	end
	pd = PgSearchDocuments.new({content: self.title, searchable_id: self.id, searchable_type: self.class.name}); pd.save
	pd = PgSearchDocuments.new({content: self.description, searchable_id: self.id, searchable_type: self.class.name}); pd.save
end


# search helpers
	def thumb
		return self.image(:thumb)
	end

	def search_valid?
		!!(approved)
	end

# image and background delete or update

	def delete_image
		@delete_image ||= "0"
	end
	def delete_image=(value)
		@delete_image = value
	end

	def delete_sidebar_image
		@delete_sidebar_image ||= "0"
	end
	def delete_sidebar_image=(value)
		@delete_sidebar_image = value
	end


	def delete_background
		@delete_background ||= "0"
	end
	def delete_background=(value)
		@delete_background = value
	end


	scope :series, -> {where(:approved => true)}



	private  
	def destroy_images?
	    # self.image.clear if @delete_image == "1"
	    # self.background.clear if @delete_background == "1"
	    self.image = nil if @delete_image == "1"
	    self.background = nil if @delete_background == "1"
	    self.sidebar_image = nil if @delete_sidebar_image == "1"
	end

	def slug_candidates
		[
			:title,
			[:title, 2],
			[:title, 3],
			[:title, 4],
			[:title, 5],
			[:title, 6],
			[:title, 7],
			[:title, 8],
			[:title, 9],
			[:title,  Time.now.strftime('%M:%S') ]
		]
	end

end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
	before_action :set_friend, only: [:show, :edit, :update, :destroy, :follow, :unfollow]


	def index
		# redirect_to "/"
		@title = "Friends"
		@active = "friends"
		@friends=Friend.approved.paginate(:page => params[:page], :per_page => 8).order(created_at: :desc) 
	    @description = "Check out these cool videos from batteryPOP's coolest friends!"
	    @banner_ad = "/31902320/Friends_Main_728x90"
   		@banner_id = 'div-gpt-ad-1413353004265-0'
   		# custom code if exists
   		# @dfp_header_code = @friend.dfp_header_code
   		# @dfp_banner_ad = @friend.dfp_banner_ad
   		# @dfp_mid_side_ad = @friend.dfp_mid_side_ad
	end

	def show
		if @friend.approved
			@banner_ad = "/31902320/Friends_single_leaderboard"
   			@banner_id = 'div-gpt-ad-1413353029748-0'
   			@dfp_header="friends"
			@title = @friend.title

			# custom code if exists
	   		@dfp_header_code = @friend.dfp_header_code
	   		@dfp_banner_ad = @friend.dfp_banner_ad
	   		@dfp_mid_side_ad = @friend.dfp_mid_side_ad

			if @friend.background.present? 
				@custom_background = @friend.background(:original)
			end
			@custom_background_full = @friend.background_full
			
			if(@episode.nil?) 
				@episode = @friend.episodes.first
				@show = @episode.show
			end
		else
			redirect_to "/"
		end
	end

	def follow
		unless current_user.nil?
		  current_user.follow(@friend)
		  @friend_follow_status = "You are following"
		  current_user.touch  # cache clear; TODO: sweeper?
		end
	end

	def unfollow
		unless current_user.nil?
		  current_user.stop_following(@friend)
		   @friend_follow_status = ""
		   current_user.touch  # cache clear; TODO: sweeper?
		end
	end

	

	private
	def set_friend
		# @friend = Friend.includes(:episodes).includes(:features).where("features.active" => true).friendly.find(params[:id])
		@friend = Friend.includes(:features).friendly.find(params[:id])
	end
end

app/views/friends/_follow_friend.html.erb
    <div class='button-follow follow_friend-<%= friend.id %>'>

    <% if current_user.nil? %>

        <a class='btn btn-navy disabled' data-toggle="modal" data-target="#become_member"  href='#'>
            <h5>FOLLOW</h5>
        </a>
   

    <% else %>

      <% if current_user.following?(friend) %> 
        <%= link_to(unfollow_friend_path(friend), 
            :remote => true, 
            :class => 'btn btn-navy pop-ver', 
            :data => {:toggle=>"popover", :trigger => 'hover', :placement => 'left', :html => true,  :content => "Click to stop following <b>'#{friend.title}!'</b>"} 
            ) do %>
    		<h5>UN-FOLLOW</h5>
        <% end %>
      <% else %>
      <%= puts "FRIEND CALLED" %>
        <%= link_to(follow_friend_path(friend),
            :remote => true, 
            :class => 'btn btn-navy pop-over', 
            :data => {:toggle=>"popover", :trigger => 'hover', :placement => 'left', :html => true,  :content => "Click to follow <b>'#{friend.title}!'</b>"} 
            ) do %>
    		<h5>FOLLOW</h5>
        <%end%>
      <% end %>
    <% end %>
</div>
</div><!-- col-half2 -->

app/views/friends/follow.js.erb
$('.follow_friend-<%=@friend.id%>').replaceWith('<%= escape_javascript(render :partial => "friends/follow_friend", :locals => {:friend => @friend}) %>');
$('.pop-button').popover();

app/views/friends/index.html.erb
<%= render partial: "layouts/show_friend_listing", 
	:locals => {
		:listing_title => @title, :listing_description =>  @description,  :list_items => @friends, :list_class => "thumb-logo", :navigation => 'paginate'

} %>

app/views/friends/show.html.erb
<section class="wrapper">
	<%= get_banner_embed %>

	<!-- badge -->
	<% @action = "
	#{ render :partial => "episodes/popunpop", :locals => {:episode => @episode} }
	<div class='col-sm-12 col-xs-6'>
	#{ render :partial => "friends/follow_friend", :locals => {:friend => @friend} }
	</div>
	" %>


	<% @age_range =  (!@show.age_range.nil? && !@show.age_range.empty?) ? "<span class='episode-ages'><strong>For kids</strong> <em>#{@show.age_range}</em></span>" : '' %>

	<% 	@color_class = ''
		unless @friend.primary_color.empty? 
			@color_class = "background-color: #{@friend.primary_color};"
		end %>



	<%= render partial: "layouts/breadcrumb", :locals => {
			:crumb_creator => "#{@friend.sponsor}",
			:crumb_style => @color_class,
			:crumb_thumb  => image_tag(@friend.image(:large), :alt => @friend.sponsor, :class => ""),
			:crumb_title => @friend.title, 
		 	
		 	:crumb_text => "#{ @friend.description }<header><h1><strong>Watching:</strong> <em>#{@episode.title}</em> #{@age_range}</h1></header>".html_safe,
			:crumb_action => "#{@action}".html_safe, 
			:crumb_sponsor => !@friend.hide_sponsor_banner?
			 	} %>




	<div class="row clearfix row-featured">		
	<!-- video section -->

		<div class="col-md-12 column">

			<!-- featured area -->
			<% unless (@friend.features.empty? || is_friend_return_view?) %>

				<div class="slider slider-sponsor">
					<ul>
						<% @friend.features.each do |feature| %>
							<% @dur = feature.seconds.nil? ? "" : "duration=#{feature.seconds}"%>
							<li <%= @dur %>><%= feature.content.html_safe %></li>
						<% end %>

					</ul>
					<% if @friend.features_exit == "close" %>
						<span class="closex"></span>
					<% end %>
				</div>
			<% end %>

			<div class="videocontent">
				<% if !(@episode).nil? %>
					<%= vid_embed(@episode).html_safe  %>
				<% end %>
			</div>

			
		</div>

	<!-- end video section -->
		<%  render :partial => "layouts/next_up" %>

		<div class="corners"></div>

	</div>

	<!-- end video / nextup -->


	<div class="row clearfix">
		<!-- episode list -->
		<div class="col-md-8 column">
			
				<div class="media-list">
					<% @friend.episodes.each do |ep| %>
						<% if ep.approved? %>

						<% @age_range =  (!ep.age_range.nil? && !ep.age_range.empty?) ? "<span class='episode-age-range'>For kids #{ep.age_range}</span> " : ' ' %>
						<% (@vote == (current_user && (current_user.voted_up_on? ep))  ? "pop" : "") %>
						<div class="media <% if(@episode == ep) %>active<% end %> ">
							<a class="clearfix <% if(!@friend.hide_sponsor_listing?) %>sponsor<% end %> " href="<%= @friend.episode_link(ep) %>">
								<div class="pull-left thumb">
									<%= image_tag(ep.image(:thumb), :alt => ep.title, :class => 'media-object ') %>
								</div>
								<div class="media-body">
									<h3 class="media-heading"><%= ep.chosen_title %></h3>
									<h4><% if(!ep.duration.nil? && !ep.duration.empty?)%><%= ep.duration %><% end %></h4>
									<%= ep.description.html_safe %>
								</div>
							</a>
						

							<%= render :partial => "episodes/pop_badge", :locals => {:episode => ep}  %>
							<!-- badge -->
						</div>
						<% end %>
					<% end %>
					<!-- media -->
				</div>
			
			<!-- media list -->
		</div>
		<!-- end episode list -->

		<!-- sidebar -->

		<div class="col-md-4 column sidebar">


			<% if @friend.sidebar_image.present?  %>
				<div class="row clearfix">
					<div class="col-md-12 column">
					<%= link_to_if(@friend.sidebar_image_link?, image_tag(@friend.sidebar_image.url, :width => "100%"), @friend.sidebar_image_link ) %>
					</div>
				</div>
			<% end %>


			<!-- shows mid ads -->
				<div class="row clearfix">
					<div class="col-md-12 column">
					<!-- Shows_Single_medrec 1 -->
					<% if @dfp_mid_side_ad.nil? || @dfp_mid_side_ad.empty? %>
						<div id='div-gpt-ad-1413390818658-0' style='width:300px; height:250px;' class="webad-side-lower">
							<script type='text/javascript'>
							googletag.cmd.push(function() { googletag.display('div-gpt-ad-1413390818658-0'); });
							</script>
						</div>
					<% else %>
						<%= @dfp_mid_side_ad.html_safe %>
					<% end %>
					</div>
				</div>
				<!-- shows mid ads end -->

			

			

			<!-- small 100 stacks of 3 -->
			<div class="row clearfix">
				<div class="col-md-12 column ">
					<div class="webad-side-lower-alt webad-stack">
						<!-- Shows_single_300x100_1 -->
						<div id='div-gpt-ad-1413434995365-0' style='width:300px; height:100px;'>
							<script type='text/javascript'>
							googletag.cmd.push(function() { googletag.display('div-gpt-ad-1413434995365-0'); });
							</script>
						</div>
						<!-- Shows_single_300x100_2 -->
						<div id='div-gpt-ad-1413390931893-0' style='width:300px; height:100px;'>
							<script type='text/javascript'>
							googletag.cmd.push(function() { googletag.display('div-gpt-ad-1413390931893-0'); });
							</script>
						</div>
						<!-- Shows_single_300x100_3 -->
						<div id='div-gpt-ad-1413390956486-0' style='width:300px; height:100px;'>
							<script type='text/javascript'>
							googletag.cmd.push(function() { googletag.display('div-gpt-ad-1413390956486-0'); });
							</script>
						</div>
					</div>
				</div>
			</div>
				
		</div>
		<!-- end sidebar -->
		<!-- end lower listings -->
		

	</div>
</section>


<%= javascript_include_tag 'refresh' %>

<!-- javascript with optional params -->



<script type="text/javascript">
	$(document).ready(function(){
		<% unless @friend.features.empty? %>
			
			$('.slider.slider-sponsor ul').bxSlider({
				controls: <%= !@friend.features_autoplay %>,
		        infiniteLoop: true,
		        pager: false, 
		       <% if @friend.features_autoplay %>
				  	auto: true,
				<% end %>
				responsive: true,
				touchEnabled: true
	          	<% if @friend.features_exit == "automatic" %>
			  		, onSlideBefore: function($slideElement, oldIndex, newIndex){
					    if(newIndex == 0){
					    	$( "div.slider-sponsor" ).fadeOut(
					    		4000,
						    	$( "div.slider-sponsor" ).html("")
					    	);
					    }
					  }
				<% end %>
		    });

		<% end %>
	});
</script>

app/views/friends/unfollow.js.erb
$('.follow_friend-<%=@friend.id%>').replaceWith('<%= escape_javascript(render :partial => "friends/follow_friend", :locals => {:friend => @friend}) %>');
$('.pop-button').popover();