config/routes.rb
Batterypopv2::Application.routes.draw do


  get 'kpass/authorize' => 'kpass#authorize', as: 'kpass_authorize'
  get 'kpass/profile' => 'kpass#profile', as: 'kpass_profile'
  get 'kpass/verify' => 'kpass#verify', as: 'kpass_verify'
  get 'kpass/sign_out' => 'kpass#sign_out', as: 'kpass_sign_out'
  post 'kpass/webhooks' => 'kpass#webhooks', as: 'kpass_webhooks'
  get 'kpass/new' => 'kpass#new', as: 'kpass_new'


  mount Rich::Engine => '/rich', :as => 'rich'

  resources :channels

  resources :menus

  # resources :contacts
  #

  # mount Split::Dashboard, :at => 'admin/split'

  resources :friends do
    member do
      get :follow
      get :unfollow
    end
    resources :episodes
  end

  # resources :episodes

  resources :posts

  resources :links do
    member do
      get :file
      get :feed
    end
  end

  resources :categories

  resources :tournaments

  get "matches/:id/:episode_id", :to => "tournaments#vote"

  resources :shows do
    member do
      get :follow
      get :unfollow
    end
     resources :episodes
  end

  resources :episodes do
    member do
      get :pop
      get :unpop
      post :refresh
    end
  end

 post "/refresh", :to => "episodes#refresh"

  resources :messages
  resources :conversations


  # sitemap routing
  get "/sitemap.xml", :to => "sitemap#index"
  get "/sitemap.xml.gz", :to => "sitemap#index"

  get 'videotest', :to => "media#index"

  get "/dashboard", :to => "creators#dashboard"
  get "/creators/sign_out", :to => "creators#dashboard"


  # get "pages/search"

  get "shorts", :to => "pages#shorts"
  # get "calling-all-creators", :to => "pages#creators"
  # get "privacy-policy", :to => "pages#privacy"
  # get "terms-and-conditions", :to => "pages#terms"
  # get "advertise-with-us", :to => "pages#advertise"
  # get "about-batterypop", :to => "pages#about"
  # get "investors", :to => "pages#investors"
  get "bot", :to => "pages#bot"

  # get "test", :to => "pages#test"

  get "search", :to => "pages#search"

  get "contact", :to => "contacts#new"
  post "contact", :to => "contacts#create"

  root :to => "pages#home"




  devise_for :users,
    :controllers => {
      :registrations => "devise/custom/registrations",
      :passwords => "devise/custom/passwords",
      :sessions => "devise/custom/users"
    }

  devise_for :creators,
    :controllers => {
       sessions: "devise/custom/creators"
      # :registrations => "devise/custom/creators"
    }

  # devise_for :creators, :skip => [:sessions] do
  #   get '/creator/login' => 'devise/sessions#new', :as => :new_creator_session
  #   post '/creator/login' => 'devise/sessions#create', :as => :creator_session
  #   get 'logout' => 'devise/sessions#destroy', :as => :destroy_creator_session
  # end

    #devise_for :users, path: "auth", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }

resources :users do
    member do
      patch :save_avatar
      get :follow
      get :unfollow
     end
  end

  resources :creators  do
    member do
      post :draw_chart_bar
      post :draw_chart_donut
    end
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)


  get ":id" => "pages#show"

  get '*path' => redirect('/')



end

app/models/episode.rb
# == Schema Information
#
# Table name: episodes
#
#  id                 :integer          not null, primary key
#  title              :string(255)
#  description        :text
#  approved           :boolean
#  slug               :string(255)
#  show_id            :integer
#  embed_id           :string(255)
#  video              :string(255)
#  created_at         :datetime
#  updated_at         :datetime
#  image_file_name    :string(255)
#  image_content_type :string(255)
#  image_file_size    :integer
#  image_updated_at   :datetime
#  cached_votes_total :integer          default(0)
#  cached_votes_score :integer          default(0)
#  cached_votes_up    :integer          default(0)
#  cached_votes_down  :integer          default(0)
#  episode            :integer
#  duration           :string(255)
#  age_range          :string(255)
#

class Episode < ActiveRecord::Base
  include PgSearch
  # multisearchable :against => [:title, :description]

  after_save :set_search_link

  pg_search_scope :search_text,
    :against => [:title, :description],
    :using => {
               :tsearch => {:prefix => true}
              }


  include DashboardUtility

  has_and_belongs_to_many :episodes


	extend FriendlyId
	friendly_id :slug_candidates, use: :slugged, :use => :scoped, :scope => :show

	acts_as_votable
	acts_as_taggable_on :tags, :keywords

	belongs_to :show, touch: true
	has_one :creator, :through => :show
	belongs_to :embed
	has_many :channels, :through => :show

	# has_many :friend_episodes
	# belongs_to :friend
	has_and_belongs_to_many :friends,  :join_table => :friend_episodes, :order => "position ASC"

	has_many :links, :as => :linkedmedia
	# has_many :visits, :through => :links  -- removing visit; no reason to track

	has_many :chicago_votes, :as => :voteable

	before_save :destroy_images?


	has_attached_file :image,
	    :styles => {
	    	large: "864x486>",
	    	:thumb => "150x150#",
	    	:roku_sd => "214x144^",
	    	:roku_hd => "290x218^"

	    },
	    storage: :s3,
	    s3_credentials: "#{Rails.root}/config/amazon_s3.yml",
	    path: "images/:class/:id/:attachment/:style/:filename",
	    bucket: S3_BUCKET,
	    default_url: "/assets/missing.png"

	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

	def self.mostpopped(lim=nil	)
		# following is only TRUE votes
		#return Episode.joins(:show).where(:approved => true, "shows.approved" => true).order('cached_votes_up DESC').limit(lim).includes(:show)
		# following is chicago votes AND true votes
		# below is working for all time
		# return Episode.joins(:show).where(:approved => true, "shows.approved" => true).where("episodes.chicago is not NULL").order('(cached_votes_up + chicago) DESC').limit(lim).includes(:show)
		# below is for section of time
		# ActsAsVotable::Vote.all(:conditions => ["created_at >= ?", Date.today.at_beginning_of_month])
		# x=ActsAsVotable::Vote.all(:conditions => ["created_at >= ? AND votable_type = ?", "2014-10-01", "Episode"])
		#  x=ActsAsVotable::Vote.select("id, votable_id").all(:conditions => ["created_at >= ? AND votable_type = ?", "2014-10-01", "Episode"])
		#  x=ChicagoVote.select("voteable_id, count(voteable_id) as total").where(:created_at => @start..@end).group("voteable_id").order("total DESC")

		return Episode.joins(:show).where(:approved => true, "shows.approved" => true).where("episodes.chicago is not NULL").order('(cached_votes_up + chicago) DESC').limit(lim).includes(:show)
	end


	def self.mostpopped_by_month(lim=nil)
          Episode.mostpopped_by_range Date.today.beginning_of_month, Date.today.end_of_month, lim
	end

        def self.mostpopped_by_range(pd_start, pd_end, lim=nil)
          Episode.joins(:chicago_votes)
            .select("episodes.*, count(episodes.id) as total")
            .where(:chicago_votes => {:created_at => pd_start..pd_end })
            .group("episodes.id").order("total DESC").limit(lim)
	end

def hide_sponsor_globally?
	return true if(self.friends.approved.empty?)
	return self.friends.approved.where(hide_sponsor_globally: true).exists?
	
	# this is to control sponsor tag on most popped
	# it's sort of a sum: if a video has ANY sponsor page that says true to hiding it
	# then it's hidden on mostpopped - even if video is sponsored elsewhere
	# if(self.friends.approved.empty?) # no friend list so hide the tag
	# 	true
	# end
	# 
	# 
	
	# return true if(self.friends.approved.empty?)


	# if(!self.friends.approved.empty?) # if there's any friend page check each
	# 	puts " ----        NOT EMPTY";  
	# 	self.friends.approved.each do |f|
	# 		puts "hide globally:  #{f.hide_sponsor_globally}"
	# 		return true if(f.hide_sponsor_globally)
	# 	end
	# 	# at end of checking friends; none globally off
	# 	# 
	# 	puts "----   nope you can show sponsor"
	# 	return false
	# end
end


# popping / liking with chicago voting
def pops
	#return (self.likes.size + Integer(self.chicago.to_i))
	return (self.cached_votes_up + Integer(self.chicago.to_i))
end

# pg search fixes
def set_search_link
	ret = PgSearchDocuments.where(searchable_id: self.id, searchable_type: self.class.name)
	if ret.count
		ret.each do |d|
			d.delete
		end
	end
	pd = PgSearchDocuments.new({content: self.title, searchable_id: self.id, searchable_type: self.class.name}); pd.save
	pd = PgSearchDocuments.new({content: self.description, searchable_id: self.id, searchable_type: self.class.name}); pd.save
end


def should_generate_new_friendly_id?
  slug.blank? || title_changed?
end

#search helpers
	def link
		if(self.show.nil?)
			return  "/episodes/" + self.slug
		else
			return "/shows/" + self.show.slug + "/episodes/" + self.slug
		end
	end

	def thumb
		return (self.image(:thumb))
	end

	def poster
		return (self.image(:large))
	end

	def search_valid?
		!!(approved && self.show && self.show.search_valid?)
	end


# title function to return for slide: show + ep title or just show title if single
	def slide_title
		if !self.show.present?
			return	self.title
		end
		if self.show.present?
			if self.show.single? 
				self.show.title
			else
				self.show.title + ' :<br />' + self.title
			end
		end
	end

	def chosen_title
		if self.show.present?
			self.show.title + ' : ' + self.title
		else
			self.title
		end
	end


##  TODO NEED TO CLEAN UP BELOW
# not the best way of doing this I think
	# if (:current_user != :current_admin_user)
	# 	default_scope where(:approved => true)
	# end

	scope :approved, -> {where(:approved => true)}

	# def self.default_scope
	# 	approved
	# end



	def self.nextup(episode, lim=nil)
		# first see if taglist
		@next_episode = episode.show.episodes[episode.show.episodes.index(episode)+1]
		if(!episode.tag_list.empty?)
			@ret = Episode.tagged_with(episode.tag_list, :any => true).reject {|ep| ep == episode}
			@ret = @ret.sample(lim).uniq
			if(!@next_episode.nil?)
				@ret.unshift(@next_episode)
			end
			return @ret
		else
			# checking if this episode's show belongs to any channels
			if(!episode.show.channels.empty?)
				@all_episodes = []
				episode.channels.where(:hidden => [nil, false] ).find_each { |channel|  channel.episodes.joins(:show).where(:approved => true, "shows.approved" => true).each {|ep|  @all_episodes << ep } }
				if(lim.nil?)
					lim = @all_episodes.count
				end
				@all_episodes = @all_episodes.reject {|ep| ep == episode}
				# return (!@next_episode.nil?)  ?  @all_episodes.sample(lim).unshift(@next_episode) : @all_episodes.sample(lim)
				@all_episodes = @all_episodes.sample(lim);
				if(!@next_episode.nil?)
					@all_episodes.unshift(@next_episode)
				end
				return @all_episodes
			else
				# not belong to any channels so most popped?
				@most =   Episode.mostpopped(lim).reject{|ep| ep == episode}
				if(!@next_episode.nil?)
					@most.unshift(@next_episode)
				end
				return @most
			end
		end
	end


	def votes_by_gender
		DashboardUtility.users_to_census_gender_count(self.votes.up.by_type(User).voters, true)
	end

	def votes_by_age
		DashboardUtility.users_to_census_age_count(self.votes.up.by_type(User).voters, true)
	end

	def should_generate_new_friendly_id?
	  slug.blank? || title_changed?
	end

	# image and background delete or update

	def delete_image
		@delete_image ||= "0"
	end
	def delete_image=(value)
		@delete_image = value
	end


	private
	def destroy_images?
	    self.image = nil if @delete_image == "1"
	end

	def slug_candidates
		[
			[:title],
			[:title, 2],
			[:title, 3],
			[:title, 4],
			[:title, 5],
			[:title, 6],
			[:title, 7],
			[:title, 8],
			[:title, 9],
			[:title,  Time.now.strftime('%M:%S') ]

		]
	end

	def episode_params
		params.require(:episode).permit(:title, :description, :approved, :show_id, :slug)
	end


end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
  before_action :set_episode, only: [:show, :edit, :update, :destroy, :pop, :unpop ]


  # GET /episodes
  # GET /episodes.json
  def index
    @episodes = Episode.all
  end

  # GET /episodes/1
  # GET /episodes/1.json
  def show

    @show = @episode.show
    @followers = @show.user_followers.offset(rand(@show.user_followers.count)).limit(5)
    @likers = @episode.votes.up.by_type(User).voters.compact

    if(!@episode.tag_list.empty?)
      @page_keywords = @episode.tag_list.to_s
    end
     @description = @episode.description


     # @ga_custom = "ga('set', 'dimension1', '#{@episode.creator.id}');"
     @ga_page_params = ", {'dimension1':  '#{@episode.creator.id}', 'dimension2': '#{@episode.id}'}"

     
   # @page_keywords = "this is episode keywords"

    if params.has_key?(:show_id)
      @dfp_header = "shows"
      @banner_ad = "/31902320/Shows_Leaderboard"
      @banner_id = 'div-gpt-ad-1411894829676-0'
      @title = "#{@show.title} : #{@episode.title}"
       
       render 'shows/show'
    elsif params.has_key?(:friend_id)
      @dfp_header = "friends"
      @banner_ad = "/31902320/Friends_single_leaderboard"
      @banner_id = 'div-gpt-ad-1413353029748-0'
      @friend = Friend.friendly.find(params["friend_id"])

        # custom code if exists
      @dfp_header_code = @friend.dfp_header_code
      @dfp_banner_ad = @friend.dfp_banner_ad
      @dfp_mid_side_ad = @friend.dfp_mid_side_ad

      @title = "#{@friend.title} : #{@episode.title}"
      if @friend.background.present? 
        @custom_background = @friend.background(:original)
      end
      @custom_background_full = @friend.background_full
      render 'friends/show'
    else
      redirect_to @episode.link
    end
  end

  # GET /episodes/new
  def new
    @episode = Episode.new
  end

  # GET /episodes/1/edit
  def edit
    redirect_to "/"
  end


# voting
  def pop
    # unless current_user.nil?
    #    @episode.liked_by current_user
    # end
    if current_user.nil?
      @episode.chicago = Integer(@episode.chicago.to_i) + 1
      @episode.save
      ChicagoVote.create(:voteable => @episode)
    else
       @episode.liked_by current_user
       current_user.touch
     end
     expire_fragment("shows_most_popped")
  end

  def unpop
    unless current_user.nil?
       @episode.unliked_by current_user
      current_user.touch
       expire_fragment("shows_most_popped")
     end
  end


  def refresh
    @episode = Episode.find(params[:id]);
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_episode
      @episode = Episode.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def episode_params
      params.require(:episode).permit(:title, :description, :approved, :creator_id, :show_id, :video_type, :video_id)
    end
end

app/views/episodes/_pop_badge.html.erb
<% if(!current_user.nil? && (current_user.voted_up_on? episode)) %>

	<%= link_to(unpop_episode_path(episode), 
			:remote => true,
			:class => "badge pop-over episode-badge-vote-#{episode.id}",
			:data => {:toggle=>"popover", :trigger => 'hover', :placement => 'left', :html => true,  :content => "Click to unPOP <b>'#{episode.title}!'</b>"} 
			) do %>
	
	<h5><%= episode.pops %></h5>
	<div class="badge-box" >
		<div class="btn-pop "></div>
	</div>

	<% end %>


<% else %>

	<%= link_to(pop_episode_path(episode), 
			:remote => true,
			:class => "badge pop-over episode-badge-vote-#{episode.id}",
			:data => {:toggle=>"popover", :trigger => 'hover', :placement => 'left', :html => true, :content => "Click to POP  <b>'#{episode.title}!'</b>"}
			) do %>

	<h5><%= episode.pops %></h5>
	<div class="badge-box" >
		<div class="btn-pop "></div>
	</div>

	<% end %>

<% end %>

app/views/episodes/_popunpop.html.erb
<!-- begin button row --><div class="row clearfix">

	<div class="col-sm-12 col-xs-6">
	<div class="button-pop episode-header-vote-<%= episode.id %>" data-episode="<%= episode.id %> ">
	<% if(!current_user.nil? && (current_user.voted_up_on? episode)) %>
	
		<%= link_to(unpop_episode_path(episode), 
				:remote => true, 
		        :class => 'btn  btn-purple pop-over', 
				# :data => {:toggle=>"popover", :trigger => 'hover', :placement => 'left', :html => true,  :content => "Click to unPOP <b>'#{episode.title}!'</b>"} 
				) do %>
				<h5>unPOP it!</h5>

		<%end%>

	<% else %>

		<%= link_to(pop_episode_path(episode), 
				:remote => true, 
		        :class => 'btn btn-purple pop-over', 
				# :data => {:toggle=>"popover", :trigger => 'hover', :placement => 'left', :html => true, :content => "Click to POP  <b>'#{episode.title}!'</b>"} 
				) do %>
				<h5>POP it!</h5>
		<% end %>

	<% end %>
	<div class='pop-number'><%= episode.pops %></div>
</div>
</div><!-- col-half -->

app/views/episodes/index.html.erb
<h1>Listing episodes</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Approved</th>
      <th>Creator</th>
      <th>Show</th>
      <th>Video type</th>
      <th>Video</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @episodes.each do |episode| %>
      <tr>
        <td><%= episode.title %></td>
        <td><%= episode.description %></td>
        <td><%= episode.approved %></td>
        <td><%= episode.creator.displayname %></td>
        <td><%= episode.show_id %></td>
        <td><%= episode.embed.provider %></td>
        <td><%= episode.embed.code %></td>
        <td><%= link_to 'Show', episode %></td>
        <td><%= link_to 'Edit', edit_episode_path(episode) %></td>
        <td><%= link_to 'Destroy', episode, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Episode', new_episode_path %>

app/views/episodes/new.html.erb
<h1>New episode</h1>

<%= render 'form' %>

<%= link_to 'Back', episodes_path %>

app/views/episodes/pop.js.erb
$('.episode-header-vote-<%= @episode.id %>').replaceWith('<%= escape_javascript(render :partial => "episodes/popunpop", :locals => {:episode => @episode}) %>');
$('.episode-badge-vote-<%= @episode.id %>').replaceWith('<%= escape_javascript(render :partial => "episodes/pop_badge", :locals => {:episode => @episode}) %>');
$('.pop-over').popover();

// $('.bpop-badge .episode-badge-vote-<%=@episode.id%>').html('<%= @episode.pops %>');
// $('.bpop-badge-large .episode-badge-vote-<%=@episode.id%>').html('+<%= @episode.pops %>');
// $('.badge-box .pop_episode-<%=@episode.id%>').replaceWith('<%= escape_javascript(render :partial => "episodes/popunpop", :locals => {:episode => @episode}) %>');
//  // $('.pop-button').popover();

app/views/episodes/popunpop.erb
$('#popunpop-episode-<%=@episode.id%>').html('<%= escape_javascript(render :partial => "episodes/popunpop_link", :locals => {:episode => @episode}) %>');

app/views/episodes/popunpop.js.erb
// $('#popunpop-episode-<%=@episode.id%>').html('<%= escape_javascript(render :partial => "episodes/popunpop_link", :locals => {:episode => @episode}) %>');
alert("POP");

app/views/episodes/refresh.js.erb
// $('.follow-pop-wrap .pop_episode-<%=@episode.id%>').replaceWith('<%= escape_javascript(render :partial => "episodes/popunpop", :locals => {:episode => @episode}) %>');
// $('.badge-box .episode-badge-vote-<%=@episode.id%>').html('<%= @episode.likes.size %>');
// $('.bpop-badge-large .episode-badge-vote-<%=@episode.id%>').html('+<%= @episode.pops %>');
// $('.badge-box .pop_episode-<%=@episode.id%>').replaceWith('<%= escape_javascript(render :partial => "episodes/popunpop", :locals => {:episode => @episode}) %>');
//  $('.pop-button').popover();

// alert('refresh');

app/views/episodes/show.html.erb
<div class="main show episode">
  <div class="container">
    <div class="content">

      

<!-- top most / breadcrumb area -->
      <div class="row bpop-breadcrumb slight-shadow">
        <div class="col-lg-3 bpop-show-title text-right"><h3><%= @episode.show.title %></h3></div> 
        <div class="col-lg-6 bpop-show-description"><%= @episode.description.html_safe %></div>
        <div class="col-lg-3 bpop-show-action">
        </div>
      </div>
<!-- end top most / breadcrumb area -->
      
<!-- mid section player / carousel -->
      <div class="row">
        <!-- video player area -->
        <div class="col-lg-9 show-player">
          <%= @episode.embed.code.gsub("{{unbound view.dimensions.width}}", "100%").gsub("{{unbound view.dimensions.height}}", "100%").gsub("{{unbound view.autoplayFlag}}", "1").gsub("{{unbound view.videoId}}", @episode.video).html_safe %>

        </div>
        <!-- vertical carousel -->
        <div class="col-lg-3 show-popped-carousel">
          <div class="col-lg-12 show-most-popped-header"></div>
          <div class="col-lg-12 show-most-popped-controls">
            <span id="home-carousel-prev"></span> | <span id="home-carousel-next"></span>
          </div>
          <ul class="bxslider show-most-popped-carousel">
          </ul>
        </div>
      </div>
<!-- end mid section player / carousel -->


<!-- lower listings -->
      <div class="row show-bottom-section">

        <div class="col-lg-8 show-lower-left">
          
          <div class="media-list list-group">
            <% @episode.show.episodes_approved.each do |ep| %>

              <%= render partial: "layouts/horizontal_slide", :locals => {
                :slide_active => (@episode == ep),
                :slide_badge => '23,333',
                :slide_title => ep.title, 
                :slide_text => ep.description.html_safe, 
                :slide_image => image_tag(ep.image, :alt => ep.title, :class => "show-episode-image", :width => '125'), 
                # :slide_url => show_episode_path(@episode.show, Episode.friendly.find(ep.id))
                :slide_url => "/shows/"+ ep.show.slug + "/episodes/" + ep.slug
                } %>
            <% end %>

          </div>
        </div>

        <div class="col-lg-4 show-lower-right">
        </div>
      </div>

<!-- end lower listings -->







    </div>
  </div>
</div>

app/views/episodes/show.js.erb
// $('.badge-box .pop_episode-<%=@episode.id%>').replaceWith('<%= escape_javascript(render :partial => "episodes/popunpop", :locals => {:episode => @episode}) %>');

app/views/episodes/unpop.js.erb
$('.episode-header-vote-<%= @episode.id %>').replaceWith('<%= escape_javascript(render :partial => "episodes/popunpop", :locals => {:episode => @episode}) %>');
$('.episode-badge-vote-<%= @episode.id %>').replaceWith('<%= escape_javascript(render :partial => "episodes/pop_badge", :locals => {:episode => @episode}) %>');
$('.pop-over').popover();

// $('.bpop-badge .episode-badge-vote-<%=@episode.id%>').html('<%= @episode.pops %>');
// $('.bpop-badge-large .episode-badge-vote-<%=@episode.id%>').html('+<%= @episode.pops %>');
// $('.badge-box .pop_episode-<%=@episode.id%>').replaceWith('<%= escape_javascript(render :partial => "episodes/popunpop", :locals => {:episode => @episode}) %>');
//  // $('.pop-button').popover();