config/routes.rb
Batterypopv2::Application.routes.draw do


  get 'kpass/authorize' => 'kpass#authorize', as: 'kpass_authorize'
  get 'kpass/profile' => 'kpass#profile', as: 'kpass_profile'
  get 'kpass/verify' => 'kpass#verify', as: 'kpass_verify'
  get 'kpass/sign_out' => 'kpass#sign_out', as: 'kpass_sign_out'
  post 'kpass/webhooks' => 'kpass#webhooks', as: 'kpass_webhooks'
  get 'kpass/new' => 'kpass#new', as: 'kpass_new'


  mount Rich::Engine => '/rich', :as => 'rich'

  resources :channels

  resources :menus

  # resources :contacts
  #

  # mount Split::Dashboard, :at => 'admin/split'

  resources :friends do
    member do
      get :follow
      get :unfollow
    end
    resources :episodes
  end

  # resources :episodes

  resources :posts

  resources :links do
    member do
      get :file
      get :feed
    end
  end

  resources :categories

  resources :tournaments

  get "matches/:id/:episode_id", :to => "tournaments#vote"

  resources :shows do
    member do
      get :follow
      get :unfollow
    end
     resources :episodes
  end

  resources :episodes do
    member do
      get :pop
      get :unpop
      post :refresh
    end
  end

 post "/refresh", :to => "episodes#refresh"

  resources :messages
  resources :conversations


  # sitemap routing
  get "/sitemap.xml", :to => "sitemap#index"
  get "/sitemap.xml.gz", :to => "sitemap#index"

  get 'videotest', :to => "media#index"

  get "/dashboard", :to => "creators#dashboard"
  get "/creators/sign_out", :to => "creators#dashboard"


  # get "pages/search"

  get "shorts", :to => "pages#shorts"
  # get "calling-all-creators", :to => "pages#creators"
  # get "privacy-policy", :to => "pages#privacy"
  # get "terms-and-conditions", :to => "pages#terms"
  # get "advertise-with-us", :to => "pages#advertise"
  # get "about-batterypop", :to => "pages#about"
  # get "investors", :to => "pages#investors"
  get "bot", :to => "pages#bot"

  # get "test", :to => "pages#test"

  get "search", :to => "pages#search"

  get "contact", :to => "contacts#new"
  post "contact", :to => "contacts#create"

  root :to => "pages#home"




  devise_for :users,
    :controllers => {
      :registrations => "devise/custom/registrations",
      :passwords => "devise/custom/passwords",
      :sessions => "devise/custom/users"
    }

  devise_for :creators,
    :controllers => {
       sessions: "devise/custom/creators"
      # :registrations => "devise/custom/creators"
    }

  # devise_for :creators, :skip => [:sessions] do
  #   get '/creator/login' => 'devise/sessions#new', :as => :new_creator_session
  #   post '/creator/login' => 'devise/sessions#create', :as => :creator_session
  #   get 'logout' => 'devise/sessions#destroy', :as => :destroy_creator_session
  # end

    #devise_for :users, path: "auth", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'cmon_let_me_in' }

resources :users do
    member do
      patch :save_avatar
      get :follow
      get :unfollow
     end
  end

  resources :creators  do
    member do
      post :draw_chart_bar
      post :draw_chart_donut
    end
  end

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)


  get ":id" => "pages#show"

  get '*path' => redirect('/')



end

app/models/creator.rb
# == Schema Information
#
# Table name: creators
#
#  id                      :integer          not null, primary key
#  username                :string(255)
#  displayname             :string(255)
#  email                   :string(255)
#  encrypted_password      :string(255)
#  bio                     :text
#  created_at              :datetime
#  updated_at              :datetime
#  image_file_name         :string(255)
#  image_content_type      :string(255)
#  image_file_size         :integer
#  image_updated_at        :datetime
#  background_file_name    :string(255)
#  background_content_type :string(255)
#  background_file_size    :integer
#  background_updated_at   :datetime
#  slug                    :string(255)
#

class Creator < ActiveRecord::Base
	include PgSearch
	# multisearchable :against => [:username , :displayname, :bio]

	pg_search_scope :search_text,
                  :against => [:username, :displayname, :bio],
                  :using => {
                    :tsearch => {:prefix => true}
                  }

	extend FriendlyId
	friendly_id :slug_candidates, use: :slugged

	acts_as_messageable
	acts_as_taggable_on :keywords

	devise :database_authenticatable, :registerable, :rememberable, :trackable, :authentication_keys => [:username] 


	has_many :shows
	has_many :episodes, :through => :shows

	has_attached_file :image,
	    :styles => { hd: "1056x594>", large: "300x300>", node: "250x250>", :thumb => "100x100>" },
	    storage: :s3,
	    s3_credentials: "#{Rails.root}/config/amazon_s3.yml",
	    path: "images/creators/:id/image/:attachment/:style/:filename",
	    bucket: S3_BUCKET,
	    default_url: "/assets/missing.png"

	has_attached_file :background,
	    :styles => { full: "1600x1100>", large: "300x300>", node: "250x250>", :thumb => "100x100>" },
	    storage: :s3,
	    s3_credentials: "#{Rails.root}/config/amazon_s3.yml",
	    path: "images/creators/:id/background/:attachment/:style/:filename",
	    bucket: S3_BUCKET,
	    default_url: "/assets/missing.png"

	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
	validates_attachment_content_type :background, :content_type => /\Aimage\/.*\Z/

	validates_uniqueness_of :username
	validates_presence_of :username

# mailboxer
  def mailboxer_email(object)
    return nil
  end

#search helpers
  def title
  	return self.displayname
  end

def link
	return "/creators/" + self.slug
end

def thumb(dim=nil)
	return (self.image(:thumb, dim))
end

def search_valid?
	valid?
end

# creator vote / following lookup
def total_show_followers
	# just realized these aren't unique; need to keep as users and distinct
	self.shows.inject(0){|sum, i| sum + i.followers.size}
end

def total_show_pops
	self.shows.inject(0){|sum, i| sum + i.total_episode_pops}
end


def episodes_total_votes
end

def should_generate_new_friendly_id?
  slug.blank? || displayname_changed?
end

  	private
	def slug_candidates
		[
			:displayname,
			[:displayname, 2],
			[:displayname, 3],
			[:displayname, 4],
			[:displayname, 5],
			[:displayname, 6],
			[:displayname, 7],
			[:displayname, 8],
			[:displayname, 9],
			[:displayname,  Time.now.strftime('%M:%S') ]
		]
	end

  def creator_params
  end

end

app/controllers/creators_controller.rb
class CreatorsController<ApplicationController
	before_action :set_creator, only: [:show]

	respond_to :html, :xml, :json

	def index
		@creators = Creator.all
	end

	def show
		if !@creator.hidden?
			@title = "Creator: #{@creator.displayname}"
			@description = "Creator: #{@creator.displayname} #{@creator.bio}"
			@ga_page_params = ", {'dimension1':  '#{@creator.id}'}"

		else
			redirect_to "/"
		end
	end

	def dashboard
		# @title ="DASHBOARD"
		# ap current_creator
		
		if current_creator.nil? 
			redirect_to "/creators/sign_in"
		else
			@creator = current_creator
			@title = "Dashboard: #{current_creator.displayname}"
			# g=e.votes.up.by_type(User).voters.group_by &:gender
			# e.show.followers.group_by(&:gender)
		end
	end



	def draw_chart_bar
		@element =  params['element']
	end

	def draw_chart_donut
		@element =  params['element']
	end


	private
	def set_creator
		@creator = Creator.includes(:shows).friendly.find(params[:id])
	end
	def creator_params
		params.require(:creator).permit(:displayname, :username)
	end


	

end

app/views/creators/dashboard.html.erb
<div class="main show">
	<div class="container">
		<div class="content">

<div class="jumbotron">
 <h2><%= current_creator.displayname %></h2>
 <!-- <div class="pull-right">
 	<%= current_creator.total_show_followers %>
 </div> -->
  <p><%= link_to "Creator Log Out", destroy_creator_session_path, :method => :delete, :class => "btn btn-primary btn-small " %></p>
</div>

		




			<div class="row">

			<% current_creator.shows.find_each do | show | %>

			<ul class="media-list well">
				<li class="media">
					<a class="pull-left" href="#">
				     <%= image_tag(show.image(:thumb), :alt => show.title, :class => 'img-responsive thumbnail media-object pull-left', :width => '50') %>
				    </a>
					<div class="media-body">
						<h2 class="media-heading"><%= link_to show.title, show.link %></h2>
						Followers: <span class="badge alert-danger"><%= show.user_followers.count %></span> | Total Pops: <span class="badge alert-primary"><%= show.total_episode_pops %></span> 
					
					<div class="row chart-row">
						<div class="col-md-2 col-sm-2">

							<div class="panel panel-default">
								<div class="panel-heading">
									<h3 class="panel-title">Follower Genders</h3>
								</div>
								<div class="panel-body">
									<div id="show-gender-followers-<%= show.id %>" class="chart-donut" style="height: 150px;" data-chart="<%= chart_data_to_donut(show.followers_by_gender).to_json %>"></div>
								</div>
							</div>

						</div>
						<div class="col-md-4 col-sm-4">
							<div class="panel panel-default">
								<div class="panel-heading">
									<h3 class="panel-title">Follower Ages</h3>
								</div>
								<div class="panel-body">
									<div id="show-age-followers-<%= show.id %>" style="height: 150px;" class="chart-bar" data-chart="<%= chart_data_to_bar(show.followers_by_age).to_json %>"></div>
								</div>
							</div>
						</div>
						

						<div class="col-md-2 col-sm-2">

							<div class="panel panel-default">
								<div class="panel-heading">
									<h3 class="panel-title">Total Voters</h3>
								</div>
								<div class="panel-body">
									<div id="show-age-gender-voters-<%= show.id %>" class="chart-donut" style="height: 150px;" data-chart="<%= chart_data_to_donut(show.episodes_votes_by_gender).to_json %>"></div>
								</div>
							</div>

						</div>




						<div class="col-md-4 col-sm-4">
							<div class="panel panel-default">
								<div class="panel-heading">
									<h3 class="panel-title">Total Voters Age</h3>
								</div>
								<div class="panel-body">
									<div id="show-episode-voters-<%= show.id %>" style="height: 150px;" class="chart-bar" data-chart="<%= chart_data_to_bar(show.episodes_votes_by_age).to_json %>"></div>
								</div>
							</div>
						</div>
					</div>

						

			<!-- episodes -->
			<% unless show.single? %>
					<% show.episodes.find_each do | ep | %>
						<div class="media well well-sm">
							<a class="pull-left" href="#">
						     <%= image_tag(ep.image(:thumb), :alt => ep.title, :class => 'img-responsive thumbnail media-object pull-left', :width => '50') %>
						    </a>
							<div class="media-body nav-pills">
								<h2 class="media-heading"><%= link_to ep.title, ep.link %></h2>
								<button type="button" class="btn btn-default" disabled="disabled"><b>POPS:</b></button> 
								<button class="btn btn-warning btn-sm" type="button">
							      Anon: <span class="badge"><%= Integer(ep.chicago.to_i) %></span>
							    </button>
							    <button class="btn btn-primary btn-sm" type="button">
							      Users: <span class="badge"><%= ep.cached_votes_up %></span>
							    </button>
								
							</div>
							<div class="row chart-row">
								<div class="col-md-2 col-sm-2">
									<div class="panel panel-default">
										<div class="panel-heading">
											<h3 class="panel-title">Voter Genders</h3>
										</div>
										<div class="panel-body">
											<div id="episode-gender-<%= ep.id %>"  class="chart-donut center-block" style="height: 150px;"  data-chart="<%= chart_data_to_donut(ep.votes_by_gender).to_json %>" /></div>
										</div>
									</div>

								</div>
								<div class="col-md-8 col-sm-8">
									<div class="panel panel-default">
										<div class="panel-heading">
											<h3 class="panel-title">Voter Ages</h3>
										</div>
										<div class="panel-body">
											<div id="episode-age-<%= ep.id %>"  class="chart-bar center-block" style="height: 150px;" data-chart="<%= chart_data_to_bar(ep.votes_by_age).to_json %>" /></div>
										</div>
									</div>

								</div>
						
							</div>
							
						</div>
						<% end %>
			<% end %>
			<!-- end episodes -->
					</div>
				</li>
			</ul>


			<% end %>	

			</div>


<!--  -->
		</div>
	</div>
</div>


<script type="text/javascript">
	$(document).ready(function(){
		$(".chart-donut").each(function(){
			$.ajax({
				type: 'POST',
				url: '<%= draw_chart_donut_creator_path(@creator) %>',
				data: {element: this.id}
			})
		});

		$(".chart-bar").each(function(){
			$.ajax({
				type: 'POST',
				url: '<%= draw_chart_bar_creator_path(@creator) %>',
				data: {element: this.id}
			})
		});
		
	
	});
</script>

app/views/creators/draw_chart_bar.js.erb
var chartData = (eval($("#<%= @element %>").attr("data-chart")));
if(chartData.length == 0){
	$("#<%= @element %>").html('<div class="alert alert-warning text-center">No Data Found</div>');
}else{
	Morris.Bar({
	  element: '<%= @element %>',
	  data: eval($("#<%= @element %>").attr("data-chart")),
	  xkey: 'y',
	  ykeys: ['male', 'female', 'unknown'],
	  labels: ['Male', 'Female', 'Uknown'],
	  barColors: ["blue", "pink", "green"]
	});
}

app/views/creators/draw_chart_donut.js.erb
var chartData = (eval($("#<%= @element %>").attr("data-chart")));
if(chartData.length == 0){
	$("#<%= @element %>").html('<div class="alert alert-warning text-center">No Data Found</div>');
}else{
	Morris.Donut({
		colors: ["pink", "blue", "green"],
		element: '<%= @element %>',
		data: eval($("#<%= @element %>").attr("data-chart"))
	});
}

app/views/creators/index.html.erb
<section class="wrapper">

	<div class="row clearfix">
		<div class="col-md-12">
			<div class="banner theme-blue">
					<div class="well well-frame">
						<h1>Our Creators</h1>
						<p></p>
					</div>
			</div>
		</div>
	</div>


	<div class="row clearfix">
		<div class="col-md-12 column">
			<div class="short theme-green theme-invert">
			
				<% @creators.each do |creator| %>
					<% unless creator.hidden?  %>
					<% cache creator do %>
						<div class="col-md-3 col-sm-4 col-xs-6 item">
						
							<%= render partial: "layouts/vertical_slide", :locals => {
								:slide_title => creator.displayname, 
								:slide_text => "".html_safe,
								:slide_image => image_tag(creator.thumb),
								:slide_url => creator.link} %>


						</div>
					<% end %>
					<% end %>
				<% end %>


			</div>
		</div>	
	</div>
</section>

app/views/creators/show.html.erb
<section class="wrapper">


<!-- breadcrumb -->

<% @action = "" %>
<%= render partial: "layouts/breadcrumb", :locals => {
		:crumb_class => "",
		:crumb_thumb =>  image_tag(@creator.image(:large), :alt => @creator.displayname),
		:crumb_title => @creator.displayname, 
	 	:crumb_text => "#{ @creator.bio }<br /><div class='totals'>
			<div class='vote-totals'><h4>Total Show Pops: #{@creator.total_show_pops}</h4></div><div class='follow-totals'><h4>Total Show Follows: #{@creator.total_show_followers}</h4></div></div>".html_safe,
		:crumb_action => @action.html_safe
		 	} %>

<!-- end breadcrumb -->


<!-- bio area -->
<!-- end bio area -->




<!-- show list -->
<% if !@creator.shows.series.empty? %>
	<!-- page header; break off? -->

		<div class="row clearfix">
		    <div class="col-md-12">

		      <div class="banner theme-blue">
		          <div class="well well-frame">
		            <h1><%= @creator.displayname %> SHOWS</h1>
		          </div>
		      </div>

		    </div>
		  </div>

	<!-- page header end; break off? -->




	<% pos =0 %>
	<% @creator.shows.series.each do |show| %>
	<%  
	  if(pos >= (colors.count-1)) 
	    pos =0 
	  else
	    pos = pos + 1
	  end
	%>


	<div class="row clearfix">
	    <div class="col-lg-12 column">
	      <div class="panel-split panel-frame panel panel-<%= colors[pos] %> clearfix">

	        <div class="row clearfix">
	          <div class="col-md-5 column">
	            <div class="well clearfix">
	              <a href="<%= show.link %>">
	                <div class="thumb"><%= image_tag(show.image(:thumb), :alt => show.title, :class => "show-episode-image", :width => '160') %></div>
	                <div class="summary">
	                  <h2><%= "#{show.title}" %></h2>
	                  <h5><%= show.subtitle %></h5>
	                  <%= show.description.html_safe %>
	                </div>
	              </a>
	            </div>
	          </div>
	          <div class="col-md-7 column">
	            <div class="carousel carousel-horizontal theme-<%= colors[pos] %> theme-invert">
	              <ul>
	              <% show.episodes.find_each do |episode| %>
	                <li>
	                  
	                  <%= render partial: "layouts/vertical_slide", :locals => {
	                  :slide_title => episode.slide_title.html_safe, 
	                  :slide_text => truncate_html(strip_tags(episode.description), length: 100, omission: '<b>...(more)</b>'), 
	                  :slide_image => image_tag(episode.image(:thumb), :alt => episode.title, :class => "img-responsive img-circle"),
	                  :slide_url =>  episode.link, 
	                  :slide_class => !episode.friends.approved.empty? ? "sponsor": nil

	                  } %>

	                </li>
	                <% end %>
	              </ul>
	            </div>
	          </div>
	          <!-- carousel -->
	        </div>
	        <!-- panel -->
	      </div>
	      <!-- row -->
	    </div>
	  <!-- col -->
	  </div>
	  <!-- row -->


	<!-- end lower listings -->
	<% end %>
<% end %>


<!-- end show list -->


<!-- shorts slider -->
<% if !@creator.shows.shorts.empty? %>

	<!-- page header; break off? -->

		<div class="row clearfix">
		    <div class="col-md-12">

		      <div class="banner theme-blue">
		          <div class="well well-frame">
		            <h1><%= @creator.displayname %> SHORTS</h1>
		          </div>
		      </div>

		    </div>
		  </div>

<!-- page header end; break off? -->




	<div class="row clearfix">
		<div class="col-md-12 column">
			<div class="short theme-red theme-invert">
				<div class="row clearfix">

				<% @creator.shows.shorts.each do |short| %>

					<div class="col-md-3 col-sm-4 col-xs-6 item">

						<%= render partial: "layouts/vertical_slide", :locals => {
							:slide_title => short.title, 
							:slide_text => short.description.html_safe, 
							:slide_image => image_tag(short.image(:thumb), :alt => short.title, :class => "img-responsive img-circle", :width => '110', :height => '110' ),
							# :slide_url => episode_path(Episode.friendly.find(short.episodes.first.id))
							:slide_url => "/shows/" + short.slug 

							} %>

					</div>

				<% end %>
				</div>
			</div>
		</div>
	</div>






<% end %>
<!-- end shorts slider -->


</section>